on:
  push:
    branches:
      - "master"

jobs:
  container-push:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        run: |
          tag="ghcr.io/$GITHUB_REPOSITORY_OWNER/openssh"
          docker build -t ${tag} .
          docker push ${tag}

